//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escritorio.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViajeM", Namespace="http://schemas.datacontract.org/2004/07/NegocioEmp.Entidad")]
    [System.SerializableAttribute()]
    public partial class ViajeM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Destino_ViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Hora_Fin_ViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Hora_Inicio_ViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_VehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_ViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_PasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Origen_ViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Placa_VehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino_Viaje {
            get {
                return this.Destino_ViajeField;
            }
            set {
                if ((object.ReferenceEquals(this.Destino_ViajeField, value) != true)) {
                    this.Destino_ViajeField = value;
                    this.RaisePropertyChanged("Destino_Viaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Fin_Viaje {
            get {
                return this.Hora_Fin_ViajeField;
            }
            set {
                if ((this.Hora_Fin_ViajeField.Equals(value) != true)) {
                    this.Hora_Fin_ViajeField = value;
                    this.RaisePropertyChanged("Hora_Fin_Viaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Inicio_Viaje {
            get {
                return this.Hora_Inicio_ViajeField;
            }
            set {
                if ((this.Hora_Inicio_ViajeField.Equals(value) != true)) {
                    this.Hora_Inicio_ViajeField = value;
                    this.RaisePropertyChanged("Hora_Inicio_Viaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Empleado {
            get {
                return this.Id_EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_EmpleadoField, value) != true)) {
                    this.Id_EmpleadoField = value;
                    this.RaisePropertyChanged("Id_Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Vehiculo {
            get {
                return this.Id_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_VehiculoField, value) != true)) {
                    this.Id_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Viaje {
            get {
                return this.Id_ViajeField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_ViajeField, value) != true)) {
                    this.Id_ViajeField = value;
                    this.RaisePropertyChanged("Id_Viaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Empleado {
            get {
                return this.Nombre_EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_EmpleadoField, value) != true)) {
                    this.Nombre_EmpleadoField = value;
                    this.RaisePropertyChanged("Nombre_Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Pasajero {
            get {
                return this.Nombre_PasajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_PasajeroField, value) != true)) {
                    this.Nombre_PasajeroField = value;
                    this.RaisePropertyChanged("Nombre_Pasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origen_Viaje {
            get {
                return this.Origen_ViajeField;
            }
            set {
                if ((object.ReferenceEquals(this.Origen_ViajeField, value) != true)) {
                    this.Origen_ViajeField = value;
                    this.RaisePropertyChanged("Origen_Viaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa_Vehiculo {
            get {
                return this.Placa_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Placa_VehiculoField, value) != true)) {
                    this.Placa_VehiculoField = value;
                    this.RaisePropertyChanged("Placa_Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceViaje")]
    public interface IServiceViaje {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/RegistrarViajes", ReplyAction="http://tempuri.org/IServiceViaje/RegistrarViajesResponse")]
        string RegistrarViajes(string IdEmpleado, string origenViaje, string DestinoViaje, string NombrePasajero, string id_Vehiculo, System.DateTime HoraInicio, System.DateTime HoraFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/RegistrarViajes", ReplyAction="http://tempuri.org/IServiceViaje/RegistrarViajesResponse")]
        System.Threading.Tasks.Task<string> RegistrarViajesAsync(string IdEmpleado, string origenViaje, string DestinoViaje, string NombrePasajero, string id_Vehiculo, System.DateTime HoraInicio, System.DateTime HoraFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/RegistrarViajes2", ReplyAction="http://tempuri.org/IServiceViaje/RegistrarViajes2Response")]
        string RegistrarViajes2(int IdTipoDocuemnto, string IdNumeroDocumento, string origenViaje, string DestinoViaje, string NombrePasajero, string Placa, System.DateTime HoraInicio, System.DateTime HoraFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/RegistrarViajes2", ReplyAction="http://tempuri.org/IServiceViaje/RegistrarViajes2Response")]
        System.Threading.Tasks.Task<string> RegistrarViajes2Async(int IdTipoDocuemnto, string IdNumeroDocumento, string origenViaje, string DestinoViaje, string NombrePasajero, string Placa, System.DateTime HoraInicio, System.DateTime HoraFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/BuscarViajesTodos", ReplyAction="http://tempuri.org/IServiceViaje/BuscarViajesTodosResponse")]
        Escritorio.ServiceReference1.ViajeM[] BuscarViajesTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/BuscarViajesTodos", ReplyAction="http://tempuri.org/IServiceViaje/BuscarViajesTodosResponse")]
        System.Threading.Tasks.Task<Escritorio.ServiceReference1.ViajeM[]> BuscarViajesTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/BuscarViajes", ReplyAction="http://tempuri.org/IServiceViaje/BuscarViajesResponse")]
        Escritorio.ServiceReference1.ViajeM[] BuscarViajes(System.DateTime RangoInicial, System.DateTime RangoFinal, string IdVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/BuscarViajes", ReplyAction="http://tempuri.org/IServiceViaje/BuscarViajesResponse")]
        System.Threading.Tasks.Task<Escritorio.ServiceReference1.ViajeM[]> BuscarViajesAsync(System.DateTime RangoInicial, System.DateTime RangoFinal, string IdVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/BuscarViajes2", ReplyAction="http://tempuri.org/IServiceViaje/BuscarViajes2Response")]
        Escritorio.ServiceReference1.ViajeM[] BuscarViajes2(System.DateTime RangoInicial, System.DateTime RangoFinal, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceViaje/BuscarViajes2", ReplyAction="http://tempuri.org/IServiceViaje/BuscarViajes2Response")]
        System.Threading.Tasks.Task<Escritorio.ServiceReference1.ViajeM[]> BuscarViajes2Async(System.DateTime RangoInicial, System.DateTime RangoFinal, string placa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceViajeChannel : Escritorio.ServiceReference1.IServiceViaje, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceViajeClient : System.ServiceModel.ClientBase<Escritorio.ServiceReference1.IServiceViaje>, Escritorio.ServiceReference1.IServiceViaje {
        
        public ServiceViajeClient() {
        }
        
        public ServiceViajeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceViajeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceViajeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceViajeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegistrarViajes(string IdEmpleado, string origenViaje, string DestinoViaje, string NombrePasajero, string id_Vehiculo, System.DateTime HoraInicio, System.DateTime HoraFin) {
            return base.Channel.RegistrarViajes(IdEmpleado, origenViaje, DestinoViaje, NombrePasajero, id_Vehiculo, HoraInicio, HoraFin);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarViajesAsync(string IdEmpleado, string origenViaje, string DestinoViaje, string NombrePasajero, string id_Vehiculo, System.DateTime HoraInicio, System.DateTime HoraFin) {
            return base.Channel.RegistrarViajesAsync(IdEmpleado, origenViaje, DestinoViaje, NombrePasajero, id_Vehiculo, HoraInicio, HoraFin);
        }
        
        public string RegistrarViajes2(int IdTipoDocuemnto, string IdNumeroDocumento, string origenViaje, string DestinoViaje, string NombrePasajero, string Placa, System.DateTime HoraInicio, System.DateTime HoraFin) {
            return base.Channel.RegistrarViajes2(IdTipoDocuemnto, IdNumeroDocumento, origenViaje, DestinoViaje, NombrePasajero, Placa, HoraInicio, HoraFin);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarViajes2Async(int IdTipoDocuemnto, string IdNumeroDocumento, string origenViaje, string DestinoViaje, string NombrePasajero, string Placa, System.DateTime HoraInicio, System.DateTime HoraFin) {
            return base.Channel.RegistrarViajes2Async(IdTipoDocuemnto, IdNumeroDocumento, origenViaje, DestinoViaje, NombrePasajero, Placa, HoraInicio, HoraFin);
        }
        
        public Escritorio.ServiceReference1.ViajeM[] BuscarViajesTodos() {
            return base.Channel.BuscarViajesTodos();
        }
        
        public System.Threading.Tasks.Task<Escritorio.ServiceReference1.ViajeM[]> BuscarViajesTodosAsync() {
            return base.Channel.BuscarViajesTodosAsync();
        }
        
        public Escritorio.ServiceReference1.ViajeM[] BuscarViajes(System.DateTime RangoInicial, System.DateTime RangoFinal, string IdVehiculo) {
            return base.Channel.BuscarViajes(RangoInicial, RangoFinal, IdVehiculo);
        }
        
        public System.Threading.Tasks.Task<Escritorio.ServiceReference1.ViajeM[]> BuscarViajesAsync(System.DateTime RangoInicial, System.DateTime RangoFinal, string IdVehiculo) {
            return base.Channel.BuscarViajesAsync(RangoInicial, RangoFinal, IdVehiculo);
        }
        
        public Escritorio.ServiceReference1.ViajeM[] BuscarViajes2(System.DateTime RangoInicial, System.DateTime RangoFinal, string placa) {
            return base.Channel.BuscarViajes2(RangoInicial, RangoFinal, placa);
        }
        
        public System.Threading.Tasks.Task<Escritorio.ServiceReference1.ViajeM[]> BuscarViajes2Async(System.DateTime RangoInicial, System.DateTime RangoFinal, string placa) {
            return base.Channel.BuscarViajes2Async(RangoInicial, RangoFinal, placa);
        }
    }
}
